# Generated by Django 2.1.5 on 2019-01-26 16:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=255)),
                ('grade', models.IntegerField(blank=True, default=1)),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='Logo')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='Logo')),
                ('status', models.CharField(blank=True, default='new', max_length=20)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('recipient', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=8)),
                ('fee', models.IntegerField()),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method', models.CharField(blank=True, max_length=20)),
                ('total', models.IntegerField(blank=True)),
                ('c_number', models.IntegerField()),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Problem_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='Logo')),
                ('status', models.CharField(blank=True, default='new', max_length=20)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Re_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='Logo')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('comment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Re_complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='Logo')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('complaint_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Re_problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='Logo')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('problem_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Problem_report')),
            ],
        ),
        migrations.CreateModel(
            name='Return_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, default='new', max_length=20)),
                ('complaint_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Return_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True)),
                ('total', models.IntegerField(blank=True)),
                ('status', models.CharField(blank=True, default='on hold', max_length=20)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item'),
        ),
        migrations.AddField(
            model_name='return_service',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Return_type'),
        ),
        migrations.AddField(
            model_name='problem_report',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Problem_type'),
        ),
        migrations.AddField(
            model_name='pay',
            name='shopping_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Shopping_cart'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Delivery_company'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='shopping_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Shopping_cart'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='shopping_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Shopping_cart'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Complaint_type'),
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item'),
        ),
    ]
