# Generated by Django 2.1.5 on 2019-01-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190127_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ManyToManyField(to='catalog.Type'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='phone',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='recipient',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery_company',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='delivery_company',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='delivery_company',
            name='phone',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='org/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(default='disable', max_length=20),
        ),
        migrations.AlterField(
            model_name='pay',
            name='pay_method',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pay',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='problem_report',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='problem_report',
            name='status',
            field=models.CharField(default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='re_comment',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='re_complaint',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='re_problem',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='return_service',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='return_service',
            name='status',
            field=models.CharField(default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='status',
            field=models.CharField(default='on hold', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='total',
            field=models.IntegerField(),
        ),
    ]
